name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux
            os: ubuntu-latest
          - target: windows
            os: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install
        run: npm install
      
      - name: Copy on windows
        if: ${{ matrix.target == 'windows' }}
        run: |
          cp (Get-Command node).source hello
      
      - name: Copy on linux
        if: ${{ matrix.target != 'windows' }}
        run: |
          cp $(command -v node) hello 

      - name: Build
        run: |
          node --experimental-sea-config sea-config.json
          npx postject hello NODE_SEA_BLOB sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2 
          ./hello world
      
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./hello